openapi: 3.0.1
info:
  title: REST API for template
  version: v1
paths:
  /tasks:
    get:
      servers:
        - url: https://localhost:1234/api/v1/
      description: Список задач
      tags:
        - tasks
      security:
        - authJWT:
          - read
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Фильтр по наименованию
          example: задача1
        - in: query
          name: offset
          schema: 
            type: number
          required: false
          description: Смещение относительно начала списка задач
          example: 0
        - in: query
          name: limit
          schema:
            type: number
          required: false
          description: Количество строк в результирующей выборке
          example: 10
        - in: query
          name: sort
          schema:
            type: string
          required: false
          description: Поле сортировки результата
          example: name
        - in: query
          name: order
          schema:
            type: string
            enum:
              - desc
              - asc
          required: false
          description: Направление сортировки результата
          example: desc
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                tasksExample:
                  summary: Пример ответа на запрос списка задач
                  value:
                    - id: 1
                      name: задача 1
                      search: задача 1 иванов петров
                      createdAt: '2024-10-10T10:00:01'
                      createdBy: Иванов
                      updateAt: '2024-09-09T09:09:09'
                      updateBy: Петров
                    - id: 2
                      name: задача 2
                      search: задача 2 сидоров травкин
                      createdAt: '2024-10-10T10:00:01'
                      createdBy: Травкин
                      updateAt: '2024-09-09T09:09:09'
                      updateBy: Сидоров
    post:
      servers:
        - url: https://localhost:1234/api/v1/
      description: Создание задачи
      tags:
        - tasks
      security:
        - authJWT:
          - write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
            examples:
              taskExample:
                summary: Пример создания задачи
                value:
                  name: "задача 1"
      responses:
        '201':
          description: Задача успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                taskExample:
                  summary: Пример ответа на создание задачи
                  value:
                    id: 1
                    name: задача 1
                    search: задача 1 иванов петров
                    createdAt: '2024-10-10T10:00:01'
                    createdBy: Иванов
                    updateAt: '2024-09-09T09:09:09'
                    updateBy: Петров
  /tasks/{id}:
    get:
      servers:
        - url: https://localhost:1234/api/v1/
      description: Получение задачи по ID
      tags:
        - tasks
      security:
        - authJWT:
          - read
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Уникальный идентификатор задачи
          example: 1
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                taskExample:
                  summary: Пример ответа на получение задачи
                  value:
                    id: 1
                    name: задача 1
                    search: задача 1 иванов петров
                    createdAt: '2024-10-10T10:00:01'
                    createdBy: Иванов
                    updateAt: '2024-09-09T09:09:09'
                    updateBy: Петров
        '404':
          description: Задача не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      servers:
        - url: https://localhost:1234/api/v1/
      description: Обновление задачи
      tags:
        - tasks
      security:
        - authJWT:
          - write
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Уникальный идентификатор задачи
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
            examples:
              taskExample:
                summary: Пример обновления задачи
                value:
                  name: "задача 1 (обновленная)"
      responses:
        '200':
          description: Задача успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                taskExample:
                  summary: Пример ответа на обновление задачи
                  value:
                    id: 1
                    name: задача 1 (обновленная)
                    search: задача 1 (обновленная) иванов петров
                    createdAt: '2024-10-10T10:00:01'
                    createdBy: Иванов
                    updateAt: '2024-09-09T09:09:09'
                    updateBy: Петров
    delete:
      servers:
        - url: https://localhost:1234/api/v1/
      description: Удаление задачи
      tags:
        - tasks
      security:
        - authJWT:
          - delete
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Уникальный идентификатор задачи
          example: 1
      responses:
        '204':
          description: Задача успешно удалена
        '404':
          description: Задача не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор
          example: 1
        name:
          type: string
          description: Наименование
          example: "Пример задачи"
        search:
          type: string
          description: Поисковая строка
          example: "пример задачи"
        createdAt:
          type: string
          format: date-time
          description: Дата создания
          example: '2024-10-10T10:00:01'
        createdBy:
          type: string
          description: Создано кем
          example: Иванов
        updatedAt:
          type: string
          format: date-time
          description: Дата обновления
          example: '2024-09-09T09:09:09'
        updatedBy:
          type: string
          description: Обновлено кем
          example: Петров
      required:
        - name
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  responses:
    Unauthorized:
      description: Ошибка авторизации
      content:
        application/json:
          schema:
            properties:
              Error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
    Error400:
      description: Ошибка
      content:
        application/json:
          schema:
            properties:
              Error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  stack:
                    type: string
                required:
                  - code
                  - message
security:
  - JWT: []
